### ISSUE TITLE
TS的讨论

### ISSUE THREAD

**Issue by wangjq4214** [14Days/front-mini#4]
究竟要不要写ts？我建议要不只有在state和props加强就好了 其他的我们快速做完吧

**Comment by qkuns** [comment]
我觉得可，所有地方都写TS有点麻烦了，可以在迭代的时候完善。

**Comment by wangjq4214** [comment]
我觉得TS的写法还是在如果是接口的话要以大写I开头 比如IState IProps @qkuns @BLANKMYMIND

**Comment by qkuns** [comment]
👌
